---
# Welcome to LaoWang Nav! To get started, run `docker compose up -d`
# You can configure your container here, by modifying this file
version: "3.8"
services:
  laowang-nav:
    container_name: laowang-nav

    # Pull latest image from DockerHub
    image: ghcr.io/tony-wang1990/laowang-nav:latest

    # To build from source, replace the image line with 'build: .'
    # build: .

    # You can also use an image with a different tag, e.g:
    # image: ghcr.io/tony-wang1990/laowang-nav:3.1.1

    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
    # - /path/to/my-config.yml:/app/user-data/conf.yml
    # - /path/to/item-icons:/app/user-data/item-icons/

    # Set port that web service will be served on. Keep container port as 8080
    ports:
      - 3000:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000

    # Specify restart policy
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
